

<!--SMS mobile num-->

<div class="popup-box zoom-anim-dialog  popup-sec mfp-hide form-theme5" id="sms-mobile-num">
    <div class="popup-in">
        <form class="add-new">
            <div class="pop-tl btm-bdr">
                <h3>SMS</h3> </div>

            <div class="row row-sm">
                <div class="col-sm-12">
                    <p>Enter your Mobile No.</p>
                </div>
                <div class="col-sm-9">
                    <input type="text" class="form-control" placeholder="Mobile No">
                </div>
                <div class="col-sm-3">
                    <a href="#popup-sms-sucess" class="btn  btn-blue popup-inline">Submit</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="popup-box zoom-anim-dialog  popup-sec mfp-hide form-theme5" id="popup-sms-sucess">
    <div class="popup-in add-new">
        <div class="pop-tl btm-bdr">
            <h3>SMS</h3> </div>
        <hr>
        <p class="top-gap-sm btm-gap-md txt-md"><i class="fa fa-check green-txt"></i> Your message sent successfully.</p>
    </div>
</div>
<!--Email-->
<div class="popup-box zoom-anim-dialog popup-sec mfp-hide form-theme5" id="email-pop">
    <div class="popup-in">
        <form class="add-new">
            <div class="pop-tl btm-bdr">
                <h3>Email</h3> </div>

            <div class="row row-sm">
                <div class="col-sm-12">
                    <p>Enter your Email</p>
                </div>
                <div class="col-sm-9">
                    <input type="text" class="form-control" placeholder="Email">
                </div>
                <div class="col-sm-3">
                    <a href="#popup-email-sucess" class="btn  btn-blue popup-inline">Submit</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="popup-box zoom-anim-dialog  popup-sec mfp-hide form-theme5" id="popup-email-sucess">
    <div class="popup-in add-new">
        <div class="pop-tl btm-bdr">
            <h3>Email</h3> </div>
        <hr>
        <p class="top-gap-sm btm-gap-md"><i class="fa fa-check green-txt"></i> Your Email sent successfully.</p>
    </div>
</div>
<!--14Sep2018 End-->



<!--Send Enquiry Popup 29Oct2018 Start-->
<div class="popup-box zoom-anim-dialog mfp-hide type05" id="request-info-popup">
    <div class="popup-in">
           <div class="pop-tl"><h2>Send Enquiry </h2></div>
            <div class="common-popup-cont">
                <form class="app-status-form"  name="book-now-popup">
                    <div class="row row-md">
                        <div class="col-sm-6 col-mobi-12 text-center">
                            <p>Want to know more about <strong>‘Golf in Golden Triangle’</strong></p>
                            <div class="btn-cont">
                            <a class="btn btn-blue btn-lg popup-inline" href="#rcb-popup">Click Here</a>
                                </div>
                            <span class="vert-seprter"><span> or </span> </span>
                        </div>
                        <div class="col-sm-6 col-mobi-12  text-center pop-divider">
                             <p>If you are looking for a customised holiday</p>
                            <div class="btn-cont">
                            <a class="btn btn-blue btn-lg" href="/golf/enquiry-form-01.shtml">Click Here</a>
                            </div>
                        </div>
                    </div>
            </form></div>
        </div>
</div>
<div class="popup-box zoom-anim-dialog mfp-hide type05" id="rcb-popup">
    <div class="popup-in">
        <div class="pop-tl">
            <h2>Send Enquiry - <span> Golf in Golden Triangle</span></h3>     
            <p>Please fill the form below and we will get back to you.</p>
        </div>       
            
            <div class="common-popup-cont form-theme2">
                <form class="app-status-form"  name="book-now-popup">
                    <div class="row row-md">
                        <div class="col-sm-6 col-mobi-12">
                            <div class="custom-field">
                                <div class="holder">
                                    <span>First Name<sup>*</sup></span>
                                </div>
                                <input class="" type="text" name="trav[0][firstname]" id="firstname-0">
                            </div>
                        </div>
                        <div class="col-sm-6 col-mobi-12">
                            <div class="custom-field">
                                <div class="holder">
                                    <span>Last Name<sup>*</sup></span>
                                </div>
                            <input class="" type="text" name="trav[0][firstname]" id="lastname-0">
                            </div>
                        </div>
                        <div class="col-sm-6 col-mobi-12">
                            <div class="custom-field">
                                <div class="holder">
                                    <span>Email<sup>*</sup></span>
                                </div>
                            <input class="" type="email" name="trav[0][email]" id="email-0" value="">
                            </div>
                        </div>
                        <div class="col-sm-6 col-mobi-12">
                            <div class="custom-field">
                                <div class="holder">
                                    <span>Mobile No.<sup>*</sup></span>
                                </div>
                            <input class="" type="text" name="trav[0][phone_num]" id="phone_num-0" value="" maxlength="15">
                            </div>
                        </div>
                        
                        <div class="col-sm-6 col-mobi-12 passenger-input">
                            <label class="frm-txt-sub btm-gap-sm">No. of Passengers</label>
                            <div class="row row-sm">
                                <div class="col-sm-6 col-mobi-12">
                                <select class="sm">
                                    <option selected>Adult</option>
                                    <option>01</option>
                                    <option>02</option>
                                </select>
                            </div>
                            <div class="col-sm-6 col-mobi-12">
                                <select class="sm">
                                    <option selected>Child</option>
                                    <option>01</option>
                                    <option>02</option>
                                </select>
                            </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-mobi-12">
                             <div class="custom-field">
                                
                            <textarea rows="6" name="trav[0][special_requirements]" id="spe_req" placeholder="Any special request and expectations"></textarea>
                             </div>
                        </div>
                        <div class="col-sm-12 col-mobi-12">
                            <div class="capcha type02">
                                <div class="switch-field">
                                    
                                    <div class="btn-cont">
                                        <!--<a class="btn btn-o cust-jrny" href="#">Back</a>-->
                                        <a href="#send-enq-otp-popup" class="btn btn-blue  popup-inline">Continue</a>
                                         <a href="#request-info-popup" class="btn btn-white popup-inline">Back</a>
                                    </div>

                                    <div class="latest-deals">
                                        <label><input class="" name="email_update" type="checkbox" value="yes" checked="checked"> Yes, I would like to receive the latest deals plus more free content from Golf Journeys 360.</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form></div>
        </div>
</div>

<div class="popup-box zoom-anim-dialog mfp-hide type05" id="send-enq-otp-popup">
   <div class="popup-in">
         <div class="pop-tl">
            <h2>Send Enquiry - <span> Golf in Golden Triangle</span></h3>     
            <p><b>One Time Password (OTP) Authentication</b></p>
        </div>  
        <div class="common-popup-cont form-theme2">            
            <div class="otp-sec app-status-form">
                <label class="frm-txt-sub btm-gap-sm">OTP sent to your Mobile Number <strong class="txt-red">(983454349)</strong> Please check</label>
                <div class="otp-input row">
                    <div class="col-sm-9 custom-field">                        
                        <input type="text" placeholder="Enter OTP Here">
                    </div>
                    <div class="col-sm-3 text-right">
                    <a href="#" class="otp-link btn-readmore">Resend OTP</a></div>
                </div>
                <br>
                <div class="btn-cont">
                    <!--<a class="btn btn-o cust-jrny" href="#">Back</a>-->
                    <a href="#send-enq-thankyou-popup" class="btn btn-blue btn-lg popup-inline">Submit</a>
                    <a href="#rcb-popup" class="btn btn btn-white btn-lg popup-inline">Back</a>
                    <span class="time-left-txt">TIme Left  <span class="txt-red">10:59</span></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="popup-box zoom-anim-dialog mfp-hide popup-sec type05" id="send-enq-thankyou-popup">
<div class="popup-in">        
    <form class="thank-you">   
        <div class="pop-tl">
            <h2>Query Submitted!</h2>                 
        </div>   
        <br>
        <p><strong> Thank you for enquiring with Golf Journeys 360 </strong></p>
        <p class="enq-ref">Your enquiry reference number is <span>#89809899.</span> Our travel expert will get in touch with you soon.</p>
        <p>Incase you wish to get in touch with us, call us on our toll free number at <span>0000 000 0000.</span></p>
    </form>        
</div>
</div>

<div class="popup-box zoom-anim-dialog mfp-hide popup-sec type05" id="send-enq-otp-popup-2">
   <div class="popup-in">         
       <h2 class="ttl">One Time Password (OTP) Authentication</h2>
        <div class="common-popup-cont form-theme2">            
            <div class="otp-sec app-status-form">
                <label class="frm-txt-sub btm-gap-sm">OTP sent to your Mobile Number <strong class="txt-red">(983454349)</strong> Please check</label>
                <div class="otp-input row row-sm">
                    <div class="col-sm-9 custom-field">                        
                        <input type="text" placeholder="Enter OTP Here">
                    </div>
                    <div class="col-sm-3 text-right">
                    <a href="#" class="otp-link btn-readmore">Resend OTP</a></div>
                </div>
                <br>
                <div class="btn-cont">
                    <!--<a class="btn btn-o cust-jrny" href="#">Back</a>-->
                    <a href="/golf/enquiry-form-02.shtml" class="btn btn-blue">Submit</a>                    
                    <span class="time-left-txt">TIme Left  <span class="txt-red">10:59</span></span>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Send Enquiry Popup 29Oct2018 End-->
<style>
    .g-adventure-popup {max-width: 615px;}
    .popup-sec.no-padding {padding: 0px;}
    .popup-sec .info-head {display: table;width: 100%;padding: 20px;min-height: 90px;}
    .popup-sec.g-adventure-popup .info-head {border-bottom: 3px solid #47268d;}
    .popup-sec.g-adventure-popup .info-head figure {width: 200px;padding-right: 15px;}
    .popup-sec.g-adventure-popup .info-head figure img {display: block;}
    .popup-sec.g-adventure-popup .info-head div span {font-size: 14px;}
    .popup-sec .info-head figure {display: table-cell;vertical-align: middle;}
    .popup-sec .info-head div {display: table-cell;vertical-align: middle;}
    .popup-sec .info-body {padding: 30px 25px;}
    .popup-sec .info-body b {display: block; font-size: 16px; margin-bottom: 10px;}
    .popup-sec .info-body p {font-size: 14px;}
    
    .cosmos-popup .info-head {background-color: #b51319;}
    .popup-sec.cosmos-popup .info-head div span {color: #fff;}
    .popup-sec.cosmos-popup .info-head figure {width: 150px;padding-right: 15px;}
    
    @media screen and (max-width:767px){
        .popup-sec.g-adventure-popup .info-head figure {width: 150px;}
    }
</style>

